name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - click=7.0
  - cloudpickle=1.5.0
  - cytoolz=0.10.1
  - jinja2
  - locket=1.0.0
  - msgpack-python=0.6.2
  - packaging=20.0
  - psutil=5.6.3
  - pyyaml
  - sortedcontainers=2.0.5
  - tblib=1.6.0
  - toolz=0.10.0
  - tornado=6.0.3
  - urllib3
  - zict=0.1.4
  # Distributed depends on the latest version of Dask
  - pip
  - pip:
    - git+https://github.com/dask/dask
  # test dependencies
  - pytest
  - pytest-cov
  - pytest-faulthandler
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-timeout
